name: ${project.name}
main: com.thekingelessar.assault.Assault
version: ${project.version}
author: TheKingElessar
softdepend: [ HolographicDisplays ]
depend: [ Citizens ]
commands:
  help:
    aliases: [ h, Help ]
    description: Explanation of commands.
    usage: |
      /help
  all:
    aliases: [ a, All ]
    description: Shows a chat message to all players in the game.
    usage: |
      /all <message>
  respawn:
    aliases: [ Respawn ]
    description: Kills you (in case you get stuck somewhere).
    usage: |
      /respawn
  forfeit:
    aliases: [ Forfeit, forfiet, Forfiet ]
    description: Toggles your vote to forfeit.
    usage: |
      /forfeit
  assaultadmin:
    description: Dev command. Kinda sus...
    usage: |
      /assaultadmin attack
      /assaultadmin coins <amount to add>
      /assaultadmin gp <amount to add>
permissions:
  assault.*:
    description: All Assault commands.
    children:
      assault.command.assaultadmin: true
      assault.help: true
      assault.all: true
      assault.respawn: true
      assault.forfeit: true
  assault.command.assaultadmin:
    description: A testing command, allowing you to skip the building phase and edit coin/GP values.
    default: op
  assault.command.help:
    description: Explanation of commands.
    default: true
  assault.command.all:
    description: Shows a chat message to all players in the game.
    default: true
  assault.command.respawn:
    description: Kills you (in case you get stuck somewhere).
    default: true
  assault.command.forfeit:
    description: Toggles your vote to forfeit.
    default: true